services:
  client:
    image: node:24-alpine
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
    working_dir: /app
    command: ["/bin/sh", "-c", "npm install && npm run dev"]
    environment:
      - VITE_API_URL=http://localhost:8000
  
  server:
    image: python:3.12-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    working_dir: /app
    command: ["/bin/sh", "-c", "pip install -r requirements.txt && python3 manage.py runserver 0.0.0.0:8000"]
    environment:
      - REDIS_HOST=cache
      - DEBUG=True
      - SECURITY_KEY=insecure-key
      - DATABASE_NAME=ipl_battle
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=database
  
  cache:
    image: redis:alpine
  
  database:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ipl_battle